version: '3.2'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - PORT=5000
      - LOGGER_LEVEL=DEBUG
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - browser-chrome

  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - SE_OPTS="--no-sandbox --disable-dev-shm-usage"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

volumes:
  changedetection-data:
